### ISSUE TITLE
Does not function when using the "Pop-out chat" function.

### ISSUE THREAD

**Issue by Fruktlimpa** [fiahfy/youtube-live-chat-selector#13]
What the title says, if you use the "Pop-out chat" function then the extension doesn't seem to detect it and no filtering is done.
It might never have been your intention to have it work with the pop-out chat but just in-case you were unaware.
I guess this can double as a feature request since if it isn't too annoying to add that function, it would be nice to have.

Thanks in advance.

**Comment by fiahfy** [comment]
Fixed in v0.0.8
